analyzer:
  errors:
    todo: ignore
    must_be_immutable: ignore

linter:
  rules:
    - prefer_single_quotes
    - prefer_final_locals
    - omit_local_variable_types
    - prefer_const_constructors_in_immutables
    - sized_box_for_whitespace
    - prefer_const_constructors
    - unnecessary_const
    - prefer_int_literals
    - avoid_void_async
    - unawaited_futures
    - sort_constructors_first: false
